villes = [
    {'value': 'Casablanca - الدار البيضاء', 'label': 'Casablanca - الدار البيضاء', 'link': '/pharmacie-garde-casablanca.html'},
    {'value': 'Marrakech - مراكش', 'label': 'Marrakech - مراكش', 'link': '/pharmacie-garde-marrakech.html'},
    {'value': 'Tanger - طنجة', 'label': 'Tanger - طنجة', 'link': '/pharmacie-garde-tanger.html'},
    {'value': 'El Jadida - الجديدة', 'label': 'El Jadida - الجديدة', 'link': '/pharmacie-garde-el-jadida.html'},
    {'value': 'Tetouan - تطوان', 'label': 'Tetouan - تطوان', 'link': '/pharmacie-garde-tetouan.html'},
    {'value': 'Fes - فاس', 'label': 'Fes - فاس', 'link': '/pharmacie-garde-fes.html'},
    {'value': 'Meknes - مكناس', 'label': 'Meknes - مكناس', 'link': '/pharmacie-garde-meknes.html'},
    {'value': 'Agadir - أكادير', 'label': 'Agadir - أكادير', 'link': '/pharmacie-garde-agadir.html'},
    {'value': 'Safi - آسفي', 'label': 'Safi - آسفي', 'link': '/pharmacie-garde-safi.html'},
    {'value': 'Rabat - الرباط', 'label': 'Rabat - الرباط', 'link': '/pharmacie-garde-rabat.html'},
    {'value': 'Sale - سلا', 'label': 'Sale - سلا', 'link': '/pharmacie-garde-sale.html'},
    {'value': 'Khouribga - خريبكة', 'label': 'Khouribga - خريبكة', 'link': '/pharmacie-garde-khouribga.html'},
    {'value': 'Temara - تمارة', 'label': 'Temara - تمارة', 'link': '/pharmacie-garde-temara.html'},
    {'value': 'Beni Mellal - بني ملال', 'label': 'Beni Mellal - بني ملال', 'link': '/pharmacie-garde-beni-mellal.html'},
    {'value': 'Ouarzazate - ورزازات', 'label': 'Ouarzazate - ورزازات', 'link': '/pharmacie-garde-ouarzazate.html'},
    {'value': 'Nador - الناظور', 'label': 'Nador - الناظور', 'link': '/pharmacie-garde-nador.html'},
    {'value': 'Berkane - بركان', 'label': 'Berkane - بركان', 'link': '/pharmacie-garde-berkane.html'},
    {'value': 'Oujda - وجدة', 'label': 'Oujda - وجدة', 'link': '/pharmacie-garde-oujda.html'},
    {'value': 'Sefrou - صفرو', 'label': 'Sefrou - صفرو', 'link': '/pharmacie-garde-sefrou.html'},
    {'value': 'Guelmim - كلميم', 'label': 'Guelmim - كلميم', 'link': '/pharmacie-garde-guelmim.html'},
    {'value': 'Kenitra - القنيطرة', 'label': 'Kenitra - القنيطرة', 'link': '/pharmacie-garde-kenitra.html'},
    {'value': 'Errachidia - الرشيدية', 'label': 'Errachidia - الرشيدية', 'link': '/pharmacie-garde-errachidia.html'},
    {'value': 'Mohammedia - المحمدية', 'label': 'Mohammedia - المحمدية', 'link': '/pharmacie-garde-mohammedia.html'},
    {'value': 'Inezgane - إنزكان', 'label': 'Inezgane - إنزكان', 'link': '/pharmacie-garde-inezgane.html'},
    {'value': 'Berrechid - برشيد', 'label': 'Berrechid - برشيد', 'link': '/pharmacie-garde-berrechid.html'},
    {'value': 'Zagora - زاكورة‎', 'label': 'Zagora - زاكورة‎', 'link': '/pharmacie-garde-zagora.html'},
    {'value': 'Ait Melloul - آيت ملول', 'label': 'Ait Melloul - آيت ملول', 'link': '/pharmacie-garde-ait-melloul.html'},
    {'value': 'Taza - تازة', 'label': 'Taza - تازة', 'link': '/pharmacie-garde-taza.html'},
    {'value': 'Sidi Slimane - سيدي سليمان', 'label': 'Sidi Slimane - سيدي سليمان', 'link': '/pharmacie-garde-sidi-slimane.html'},
    {'value': 'Ben Guerir - ابن جرير', 'label': 'Ben Guerir - ابن جرير', 'link': '/pharmacie-garde-ben-guerir.html'},
    {'value': 'Laayoune - العيون', 'label': 'Laayoune - العيون', 'link': '/pharmacie-garde-laayoune.html'},
    {'value': 'El Kelaa Des Sraghna - القلعة السراغنة', 'label': 'El Kelaa Des Sraghna - القلعة السراغنة', 'link': '/pharmacie-garde-el-kelaa-des-sraghna.html'},
    {'value': 'Chefchaouen - شفشاون', 'label': 'Chefchaouen - شفشاون', 'link': '/pharmacie-garde-chefchaouen.html'},
    {'value': 'Selouane - سلوان', 'label': 'Selouane - سلوان', 'link': '/pharmacie-garde-selouane.html'},
    {'value': 'Deroua - الدروة', 'label': 'Deroua - الدروة', 'link': '/pharmacie-garde-deroua.html'},
    {'value': 'Tinghir - تنغير‎', 'label': 'Tinghir - تنغير‎', 'link': '/pharmacie-garde-tinghir.html'},
    {'value': 'Tikiouine - تيكيوين', 'label': 'Tikiouine - تيكيوين', 'link': '/pharmacie-garde-tikiouine.html'},
    {'value': 'Larache - العرائش', 'label': 'Larache - العرائش', 'link': '/pharmacie-garde-larache.html'},
    {'value': 'Settat - سطات', 'label': 'Settat - سطات', 'link': '/pharmacie-garde-settat.html'},
    {'value': 'Zghanghan - زغانغان', 'label': 'Zghanghan - زغانغان', 'link': '/pharmacie-garde-zghanghan.html'},
    {'value': 'El Ksiba - القصيبة', 'label': 'El Ksiba - القصيبة', 'link': '/pharmacie-garde-el-ksiba.html'},
    {'value': 'Taroudant - تارودانت', 'label': 'Taroudant - تارودانت', 'link': '/pharmacie-garde-taroudant.html'},
    {'value': 'Martil - مرتيل‎', 'label': 'Martil - مرتيل‎', 'link': '/pharmacie-garde-martil.html'},
    {'value': 'Ben Ahmed - بن احمد', 'label': 'Ben Ahmed - بن احمد', 'link': '/pharmacie-garde-ben-ahmed.html'},
    {'value': 'El Hajeb - الحاجب', 'label': 'El Hajeb - الحاجب', 'link': '/pharmacie-garde-el-hajeb.html'},
    {'value': 'Sidi Yahia Du Gharb - سيدي يحيى الغرب', 'label': 'Sidi Yahia Du Gharb - سيدي يحيى الغرب', 'link': '/pharmacie-garde-sidi-yahia-du-gharb.html'},
    {'value': 'Taourirt - تاوريرت', 'label': 'Taourirt - تاوريرت', 'link': '/pharmacie-garde-taourirt.html'},
    {'value': 'Khemisset - الخميسات', 'label': 'Khemisset - الخميسات', 'link': '/pharmacie-garde-khemisset.html'},
    {'value': 'Asilah - أصيلا', 'label': 'Asilah - أصيلا', 'link': '/pharmacie-garde-asilah.html'},
    {'value': 'El Borouj - البروج', 'label': 'El Borouj - البروج', 'link': '/pharmacie-garde-el-borouj.html'},
    {'value': 'Sidi Kacem - سيدي قاسم', 'label': 'Sidi Kacem - سيدي قاسم', 'link': '/pharmacie-garde-sidi-kacem.html'},
    {'value': 'Souk El Arba Du Gharb - سوق الاربعاء الغرب', 'label': 'Souk El Arba Du Gharb - سوق الاربعاء الغرب', 'link': '/pharmacie-garde-souk-el-arba-du-gharb.html'},
    {'value': 'Jerada - جرادة', 'label': 'Jerada - جرادة', 'link': '/pharmacie-garde-jerada.html'},
    {'value': 'Boujad - أبي الجعد', 'label': 'Boujad - أبي الجعد', 'link': '/pharmacie-garde-boujad.html'},
    {'value': 'Ain El Aouda - عين العودة', 'label': 'Ain El Aouda - عين العودة', 'link': '/pharmacie-garde-ain-el-aouda.html'},
    {'value': 'Demnate - دمنات', 'label': 'Demnate - دمنات', 'link': '/pharmacie-garde-demnate.html'},
    {'value': 'Sidi Bouzid - سيدي بوزيد', 'label': 'Sidi Bouzid - سيدي بوزيد', 'link': '/pharmacie-garde-sidi-bouzid.html'},
    {'value': 'Imouzzer Kandar - إيموزار كندر', 'label': 'Imouzzer Kandar - إيموزار كندر', 'link': '/pharmacie-garde-imouzzer-kandar.html'},
    {'value': 'Ahfir - احفير', 'label': 'Ahfir - احفير', 'link': '/pharmacie-garde-ahfir.html'},
    {'value': 'Dakhla - الداخلة', 'label': 'Dakhla - الداخلة', 'link': '/pharmacie-garde-dakhla.html'},
    {'value': 'Sebt Ouled Nemma - السبت اولاد نمة', 'label': 'Sebt Ouled Nemma - السبت اولاد نمة', 'link': '/pharmacie-garde-sebt-ouled-nemma.html'},
    {'value': 'Had Soualem - حد السوالم', 'label': 'Had Soualem - حد السوالم', 'link': '/pharmacie-garde-had-soualem.html'},
    {'value': 'Al Hoceima - الحسيمة', 'label': 'Al Hoceima - الحسيمة', 'link': '/pharmacie-garde-al-hoceima.html'},
    {'value': 'Bouknadel - بوقنادل', 'label': 'Bouknadel - بوقنادل', 'link': '/pharmacie-garde-bouknadel.html'},
    {'value': 'Oulad Teïma - أولاد تايمة', 'label': 'Oulad Teïma - أولاد تايمة', 'link': '/pharmacie-garde-oulad-teima.html'},
    {'value': 'Mechraa Bel Ksiri - مشرع بلقصيري', 'label': 'Mechraa Bel Ksiri - مشرع بلقصيري', 'link': '/pharmacie-garde-mechraa-bel-ksiri.html'},
    {'value': 'Guercif - ڭرسيف', 'label': 'Guercif - ڭرسيف', 'link': '/pharmacie-garde-guercif.html'},
    {'value': 'Ouazzane - وزان', 'label': 'Ouazzane - وزان', 'link': '/pharmacie-garde-ouazzane.html'},
    {'value': 'Ksar El Kebir - القصر الكبير', 'label': 'Ksar El Kebir - القصر الكبير', 'link': '/pharmacie-garde-ksar-el-kebir.html'},
    {'value': 'Biougra - بيوݣرى', 'label': 'Biougra - بيوݣرى', 'link': '/pharmacie-garde-biougra.html'},
    {'value': 'Figuig - فݣيݣ', 'label': 'Figuig - فݣيݣ', 'link': '/pharmacie-garde-figuig.html'},
    {'value': 'Nouasseur - النواصر', 'label': 'Nouasseur - النواصر', 'link': '/pharmacie-garde-nouasseur.html'},
    {'value': 'Beni Yakhlef - ابن يخلف', 'label': 'Beni Yakhlef - ابن يخلف', 'link': '/pharmacie-garde-beni-yakhlef.html'},
    {'value': 'El Menzel - المنزل', 'label': 'El Menzel - المنزل', 'link': '/pharmacie-garde-el-menzel.html'},
    {'value': 'Midelt - ميدلت', 'label': 'Midelt - ميدلت', 'link': '/pharmacie-garde-midelt.html'},
    {'value': 'Ben Tayeb - بن الطيب', 'label': 'Ben Tayeb - بن الطيب', 'link': '/pharmacie-garde-ben-tayeb.html'},
    {'value': 'El Harhoura - هرهورة', 'label': 'El Harhoura - هرهورة', 'link': '/pharmacie-garde-el-harhoura.html'},
    {'value': 'Skhirate - الصخيرات', 'label': 'Skhirate - الصخيرات', 'link': '/pharmacie-garde-skhirate.html'},
    {'value': 'Khénifra - خنيفرة', 'label': 'Khénifra - خنيفرة', 'link': '/pharmacie-garde-khenifra.html'},
    {'value': 'Azilal - أزيلال', 'label': 'Azilal - أزيلال', 'link': '/pharmacie-garde-azilal.html'},
    {'value': 'El Gara - الݣارة', 'label': 'El Gara - الݣارة', 'link': '/pharmacie-garde-el-gara.html'},
    {'value': 'Sidi Rahal - سيدي رحال', 'label': 'Sidi Rahal - سيدي رحال', 'link': '/pharmacie-garde-sidi-rahal.html'},
    {'value': 'Tahla - تاهلا', 'label': 'Tahla - تاهلا', 'link': '/pharmacie-garde-tahla.html'},
    {'value': 'Mehdia - مهدية', 'label': 'Mehdia - مهدية', 'link': '/pharmacie-garde-mehdia.html'},
    {'value': 'Kasba Tadla - قصبة تادلة', 'label': 'Kasba Tadla - قصبة تادلة', 'link': '/pharmacie-garde-kasba-tadla.html'},
    {'value': 'Bouznika - بوزنيقة‎', 'label': 'Bouznika - بوزنيقة‎', 'link': '/pharmacie-garde-bouznika.html'},
    {'value': 'Aït Baha - أيت باها', 'label': 'Aït Baha - أيت باها', 'link': '/pharmacie-garde-ait-baha.html'},
    {'value': 'Deroua Ouled Ziane - الدروة و أولاد زيان', 'label': 'Deroua Ouled Ziane - الدروة و أولاد زيان', 'link': '/pharmacie-garde-deroua-ouled-ziane.html'},
    {'value': 'Sidi Ifni - سيدي إفني', 'label': 'Sidi Ifni - سيدي إفني', 'link': '/pharmacie-garde-sidi-ifni.html'},
    {'value': 'Jemaa Sehaim - جمعة سحيم', 'label': 'Jemaa Sehaim - جمعة سحيم', 'link': '/pharmacie-garde-jemaa-sehaim.html'},
    {'value': 'Aïn Atiq - عين عتيق', 'label': 'Aïn Atiq - عين عتيق', 'link': '/pharmacie-garde-ain-atiq.html'},
    {'value': 'Dar Bouazza - دار بوعزة', 'label': 'Dar Bouazza - دار بوعزة', 'link': '/pharmacie-garde-dar-bouazza.html'},
    {'value': 'Sidi Bennour - سيدي بنور', 'label': 'Sidi Bennour - سيدي بنور', 'link': '/pharmacie-garde-sidi-bennour.html'},
    {'value': 'Ifrane - إفران‎', 'label': 'Ifrane - إفران‎', 'link': '/pharmacie-garde-ifrane.html'},
    {'value': 'Azrou - أزرو', 'label': 'Azrou - أزرو', 'link': '/pharmacie-garde-azrou.html'},
    {'value': 'Bouskoura - بوسكورة', 'label': 'Bouskoura - بوسكورة', 'link': '/pharmacie-garde-bouskoura.html'},
    {'value': 'Saidia - السعيدية', 'label': 'Saidia - السعيدية', 'link': '/pharmacie-garde-saidia.html'},
    {'value': 'Médiouna - مديونة', 'label': 'Médiouna - مديونة', 'link': '/pharmacie-garde-mediouna.html'},
    {'value': 'Had Aït Belfaa - حد آيت بلفاع', 'label': 'Had Aït Belfaa - حد آيت بلفاع', 'link': '/pharmacie-garde-had-ait-belfaa.html'},
    {'value': 'Al Arrui - العروي', 'label': 'Al Arrui - العروي', 'link': '/pharmacie-garde-al-arrui.html'},
    {'value': 'Oued Zem - وادي زم', 'label': 'Oued Zem - وادي زم', 'link': '/pharmacie-garde-oued-zem.html'},
    {'value': 'Boujdour - بوجدور', 'label': 'Boujdour - بوجدور', 'link': '/pharmacie-garde-boujdour.html'},
    {'value': 'Fnideq - الفنيدق‎', 'label': 'Fnideq - الفنيدق‎', 'link': '/pharmacie-garde-fnideq.html'},
    {'value': 'Youssoufia - اليوسفية', 'label': 'Youssoufia - اليوسفية', 'link': '/pharmacie-garde-youssoufia.html'},
    {'value': 'Oualidia - الوليدية', 'label': 'Oualidia - الوليدية', 'link': '/pharmacie-garde-oualidia.html'},
    {'value': 'Benslimane - ابن سليمان', 'label': 'Benslimane - ابن سليمان', 'link': '/pharmacie-garde-benslimane.html'},
    {'value': 'Essaouira - الصويرة', 'label': 'Essaouira - الصويرة', 'link': '/pharmacie-garde-essaouira.html'},
    {'value': 'Tiflet - تيفلت', 'label': 'Tiflet - تيفلت', 'link': '/pharmacie-garde-tiflet.html'},
    {'value': 'Missour - ميسور', 'label': 'Missour - ميسور', 'link': '/pharmacie-garde-missour.html'},
    {'value': 'Fkih Ben Salah - فقيه بن صالح', 'label': 'Fkih Ben Salah - فقيه بن صالح', 'link': '/pharmacie-garde-fkih-ben-salah.html'},
    {'value': 'Beni Ensar - بني نصار', 'label': 'Beni Ensar - بني نصار', 'link': '/pharmacie-garde-beni-ensar.html'}
]